name: '@ngneat/until-destroy'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.13.4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test

      - name: Run integration tests
        run: pnpm test:integration

      - name: Build library
        run: pnpm build

      - name: Build integration app in production mode
        run: pnpm build:integration

      - name: Build integration app in production mode with RxJS@6
        run: pnpm nx run integration:build-rxjs-6

      - run: pnpm nx e2e integration-e2e
      - run: pnpm nx e2e-development integration-e2e
      - run: pnpm nx e2e-development-jit integration-e2e
